openshift/prometheus

- golang-github-prometheus-prometheus.spec
The package name should be `prometheus`, not `prometheus-prometheus`.
> Fix the package name in the spec file

- Dockerfile.rhel
We need `promu` to build Prometheus but we should use the promu package instead of the upstream version because 1) we're not allowed to download stuff from the outside and 2) this promu version generates proper binaries for OCP (eg dynamically linked with glibc).
> Install promu package for OCP multistage builds

- Dockerfile
- Dockerfile.rhel
- Dockerfile.rhel7
Following up on https://github.com/prometheus/prometheus/pull/5050.
> This instruction is usually useless e.g. when using Docker's novolume-plugin and in cloud environments.
> 
> In cloud environments volumes must be mounted and there's no point in keeping Prometheus data temporary volume dir only during life-time of a container. In local environments writable layers storage is good enough for testing.
> 
> Another downside of using VOLUME instruction is it hard to undone it in child images and one would need to re-write the Dockerfile.
> 
> If there are no BC breaks after this change I think it'll make life easier for many people.
> Dockerfile: Remove VOLUME instruction

- golang-github-prometheus-prometheus.spec
@simonpasquier This bad date formatting is currently blocking the OCP 3.11 build because tito refuses to continue with a bad date format in the changelog. All I've done here is fix it to match the format from a similar change you did in the master branch.
Please merge ASAP so we can get the build running again :)
Thanks!
> Fix bad date error in 3.11 spec file

- scrape/scrape.go
- tsdb/goversion/goversion.go
Go 1.12 is available for OpenShift 4.3 and onwards.
> Remove patches required for Go < 1.12

- web/ui/ui.go
The link to the new React-based UI was already removed from the OCP
version of Prometheus to avoid getting support requests for a feature
that is still experimental upstream. However it was possible to access
this UI by accessing the /graph/new URL manually.
This change removes completely the embedded React assets from the
generated binary. Someone trying to access /graph/new URL will
encounter a 404 error.
> web/ui: disable React-based UI

- Dockerfile.ocp
Updating golang-github-prometheus-prometheus builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/golang-github-prometheus-prometheus.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
> Updating golang-github-prometheus-prometheus builder & base images to be consistent with ART

- scrape/scrape.go
- scrape/scrape_test.go
We had to put https://github.com/openshift/cluster-monitoring-operator/pull/1350 on hold till we fix label_limits issue. This is fixed upstream and this pr is cherry pick from commit edfe657b54057e427469a2151153d305270662a4
> Bug 2056802: scrape: Fix label_limits cache usage

- web/ui/.gitignore
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>
> web/ui/.gitignore: unignore generated assets for downstream build

- tsdb/chunks/head_chunks.go
- tsdb/chunks/head_chunks_test.go
Signed-off-by: Ganesh Vernekar <ganeshvern@gmail.com>
(cherry picked from commit 83d738e263da0af1d5242a45b58b3a95df70ac4f)
> OCPBUGS-2640: Fix 'invalid magic number 0' bug (#11338)

- cmd/prometheus/main.go
- go.mod
This repository carries a hot-fix from v2.28.1 upstream [1] that was later reverted [2]. For some reason, our sync workflow failed to apply the upstream revert and we're left with a patch in our downstream that isn't necessary.
[1] https://github.com/prometheus/prometheus/pull/9021 [2] https://github.com/prometheus/prometheus/pull/9121
Signed-off-by: Simon Pasquier <spasquie@redhat.com>
> Revert unwanted downstream patch

- tsdb/chunks/head_chunks.go
- tsdb/chunks/head_chunks_test.go
This PR backport the fix of 'invalid magic number 0' bug to the release 4.10.
Original PR on upstream: https://github.com/prometheus/prometheus/pull/11338
PR on release 4.11: https://github.com/openshift/prometheus/pull/143
> OCPBUGS-3078: Backkport OCPBUGS-1718 to release 4.10

- model/textparse/openmetricsparse.go
- model/textparse/openmetricsparse_test.go
Backport of f11a0d1e7e3a0f949d836ce5658ce97223e865d1 on 4.13.z.
> OCPBUGS-26423: Add Exemplars support for all time series

- .ci-operator.yaml
- Dockerfile.ocp
- go.mod
- go.sum
Supersedes https://github.com/openshift/prometheus/pull/195
> OCPBUGS-29981: Updating golang-github-prometheus-prometheus-container image to be consistent with ART for 4.16

- tsdb/wlog/watcher.go
- tsdb/wlog/watcher_test.go
The fix was merged into the remote v2.53 branch https://github.com/prometheus/prometheus/pull/14446 but hasn't been merged into main yet https://github.com/prometheus/prometheus/pull/14455
/hold
Needs backport into 4.16
> OCPBUGS-36768: cherry-pick upstream remote-write fix

- storage/remote/max_timestamp.go
- storage/remote/queue_manager.go
- storage/remote/queue_manager_test.go
- storage/remote/write.go
chore(storage/remote): collect maxTimestamp when value is 0 as well.
This change enables the PrometheusRemoteWriteBehind alert’s expression to be evaluated even when the remote endpoint has never been reached. As a result, PrometheusRemoteWriteBehind will fire to easily detect configuration mistakes (such as incorrect endpoint URLs) or unrecoverable connectivity issues.
See https://github.com/prometheus/prometheus/issues/14350 for details.
> OCPBUGS-35483: cherry-pick upstream fix to make PrometheusRemoteWriteBehind fire when remote endpoint is never reached.

- scrape/scrape.go
- scrape/scrape_test.go
cherry pick of https://github.com/prometheus/prometheus/pull/14685
/cherrypick release-4.17 release-4.16
---
So long as they specify timestamps. We don't check that the timestamps are different.
Extend test, and use client_golang/prometheus/testutil to simplify metric check.
> OCPBUGS-38622: Restore Prometheus functionality to accept samples with different timestamps from the same series in a single scrape.

- discovery/kubernetes/endpoints.go
- discovery/kubernetes/endpointslice.go
- discovery/kubernetes/kubernetes.go
- discovery/kubernetes/kubernetes_test.go
- discovery/kubernetes/node.go
- discovery/kubernetes/pod.go
cherry-picking https://github.com/prometheus/prometheus/pull/15170
> OCPBUGS-43378: fix(discovery): Handle cache.DeletedFinalStateUnknown in node informers' DeleteFunc

- discovery/kubernetes/endpoints.go
- discovery/kubernetes/endpointslice.go
- discovery/kubernetes/kubernetes.go
- discovery/kubernetes/kubernetes_test.go
- discovery/kubernetes/node.go
- discovery/kubernetes/pod.go
…rs' DeleteFunc
cherry-pick of https://github.com/prometheus/prometheus/pull/15170
> OCPBUGS-43669: fix(discovery): Handle cache.DeletedFinalStateUnknown in node informers' DeleteFunc

- cmd/prometheus/main.go
- promql/engine.go
cherry-pick of https://github.com/prometheus/prometheus/pull/15723
---
partially reverts https://github.com/prometheus/prometheus/pull/14064
fixes https://github.com/prometheus/prometheus/issues/15232
supersedes https://github.com/prometheus/prometheus/pull/15533
reusing Engine.Close() outside of tests will require more consideration.
> OCPBUGS-48273: fix(main.go): avoid closing the query engine until it is guaranteed to no longer be in use

- scrape/scrape.go
- scrape/scrape_test.go
Cherry-picking https://github.com/prometheus/prometheus/commit/e32d89af7fb8baee53770de74793e8b2fb828f52
this needs to be backported to 4.16
---
We use the cache iteration number to detect when the same metric has occurred twice in a scrape. We need to bump this number at the end of every scrape, not just successful scrapes.
The `iter` number is also used:
* After a successful scrape, to delete older metrics and metadata.
* To detect when metadata changed in this scrape.
None of those additional cases is broken by incrementing the number on error.
> OCPBUGS-53025: Scraping: Bump cache iteration after error to avoid false duplicate detection.

- scrape/helpers_test.go
- scrape/scrape.go
- scrape/scrape_test.go
cherry-picking https://github.com/openshift/prometheus/pull/245 via https://github.com/prometheus/prometheus/pull/16220
> OCPBUGS-54940: Scraping: Bump cache iteration after error to avoid false duplicate detection.

- cmd/prometheus/main.go
This commit mofifies the warning log for NFS filesystems to clarify that while
NFS is generally not recommended for Prometheus, certain POSIX-compliant NFS
implementations may be usable.
> OCPBUGS-39089: Clarify prometheus pod NFS warning message

- cmd/prometheus/main_test.go
- storage/remote/queue_manager.go
- storage/remote/queue_manager_test.go
- storage/remote/write.go
backport of https://github.com/openshift/prometheus/pull/264
---
partial cherry-pick of https://github.com/prometheus/prometheus/pull/17065 to make it easier to backport to older versions.
the new metric is "prometheus_remote_storage_queue_highest_timestamp_seconds"
> OCPBUGS-61486: chore: compute highestTimestamp at queryManager level

- cmd/prometheus/main_test.go
- storage/remote/queue_manager.go
- storage/remote/queue_manager_test.go
- storage/remote/write.go
parial cherry-pick of https://github.com/prometheus/prometheus/pull/17065 to make it easier to backport to older versions.
the new metric is "prometheus_remote_storage_queue_highest_timestamp_seconds"
> [release-4.18] OCPBUGS-61706: chore: compute highestTimestamp at queryManager level

- cmd/prometheus/main_test.go
- config/config.go
- config/config_test.go
backport of https://github.com/openshift/prometheus/pull/273 to 4.19
> OCPBUGS-62429: chore(scrape): default to legacy validation/escaping scheme until utf-8 is fully supported by prometheus-operator
